[package]
authors = ["Colin Walters <walters@verbum.org>"]
description = "Extension APIs for cap-std"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "cap-std-ext"
readme = "README.md"
repository = "https://github.com/coreos/cap-std-ext"
# Confusingly our version is one greater than cap-std for historical reasons.
version = "0.26.2"

[dependencies]
cap-tempfile = "0.25.1"

[target.'cfg(not(windows))'.dependencies]
rustix = { version = "0.35.0", features = ["procfs"] }
#rustix = { git = "https://github.com/bytecodealliance/rustix", features = ["procfs"] }

[dev-dependencies]
anyhow = "1.0"
