[package]
authors = ["Colin Walters <walters@verbum.org>"]
description = "Extension APIs for cap-std"
edition = "2018"
license = "MIT OR Apache-2.0"
name = "cap-std-ext"
readme = "README.md"
repository = "https://github.com/cgwalters/cap-std-ext"
version = "0.1.0"

[dependencies]
cap-std = "0.22"

[target.'cfg(not(windows))'.dependencies]
rustix = { version = "0.31.0", features = ["procfs"] }

[dev-dependencies]
anyhow = "1.0"
